// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/discordcallback.tsx";
import * as $1 from "./routes/api/error.tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/api/link.tsx";
import * as $4 from "./routes/api/status.tsx";
import * as $5 from "./routes/api/unlink.tsx";
import * as $6 from "./routes/api/vote.tsx";
import * as $7 from "./routes/error/[error].tsx";
import * as $8 from "./routes/index.tsx";
import * as $9 from "./routes/invite.tsx";
import * as $10 from "./routes/status.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/TopNav.tsx";

const manifest = {
  routes: {
    "./routes/api/discordcallback.tsx": $0,
    "./routes/api/error.tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/api/link.tsx": $3,
    "./routes/api/status.tsx": $4,
    "./routes/api/unlink.tsx": $5,
    "./routes/api/vote.tsx": $6,
    "./routes/error/[error].tsx": $7,
    "./routes/index.tsx": $8,
    "./routes/invite.tsx": $9,
    "./routes/status.tsx": $10,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/TopNav.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
